export const industryType = [
    { label: 'Extermination/Pest Control', value: 'Extermination/Pest Control' },
    { label: 'Farming(Animal Production)', value: 'Farming(Animal Production)' },
    { label: 'Farming(Crop Production)', value: 'Farming(Crop Production)' },
    { label: 'Fishing/Hunting', value: 'Fishing/Hunting' },
    { label: 'Landscape Services', value: 'Landscape Services' },
    { label: 'Lawn care Services', value: 'Lawn care Services' },
    { label: 'Other (Agriculture & Forestry/Wildlife)', value: 'Other (Agriculture & Forestry/Wildlife)' },

    { label: 'Consultant', value: 'Consultant' },
    { label: 'Employment Office', value: 'Employment Office' },
    { label: 'Fundraisers', value: 'Fundraisers' },
    { label: 'Going out of Business Sales', value: 'Going out of Business Sales' },
    { label: 'Marketing/Advertising', value: 'Marketing/Advertising' },
    { label: 'Non Profit Organization', value: 'Non Profit Organization' },
    { label: 'Notary Public', value: 'Notary Public' },
    { label: 'Online Business', value: 'Online Business' },
    { label: 'Other (Business & Information)', value: 'Other (Business & Information)' },
    { label: 'Publishing Services', value: 'Publishing Services' },
    { label: 'Record Business', value: 'Record Business' },
    { label: 'Retail Sales', value: 'Retail Sales' },
    { label: 'Technology Services', value: 'Technology Services' },
    { label: 'Telemarketing', value: 'Telemarketing' },
    { label: 'Travel Agency', value: 'Travel Agency' },
    { label: 'Video Production', value: 'Video Production' },

    { label: 'AC & Heating', value: 'AC & Heating' },
    { label: 'Architect', value: 'Architect' },
    { label: 'Building Construction', value: 'Building Construction' },
    { label: 'Building Inspection', value: 'Building Inspection' },
    { label: 'Concrete Manufacturing', value: 'Concrete Manufacturing' },
    { label: 'Contractor', value: 'Contractor' },
    { label: 'Engineering/Drafting', value: 'Engineering/Drafting' },
    { label: 'Equipment Rental', value: 'Equipment Rental' },
    { label: 'Other (Construction/Utilities/Contracting)', value: 'Other (Construction/Utilities/Contracting)' },
    { label: 'Plumbing', value: 'Plumbing' },
    { label: 'Remodeling', value: 'Remodeling' },
    { label: 'Repair/Maintenance', value: 'Repair/Maintenance' },

    { label: 'Child Care Services', value: 'Child Care Services' },
    { label: 'College/Universities', value: 'College/Universities' },
    { label: 'Cosmetology School', value: 'Cosmetology School' },
    { label: 'Elementary & Secondary Education', value: 'Elementary & Secondary Education' },
    { label: 'GED Certification', value: 'GED Certification' },
    { label: 'Other (Education)', value: 'Other (Education)' },
    { label: 'Private School', value: 'Private School' },
    { label: 'Real Estate School', value: 'Real Estate School' },
    { label: 'Technical School', value: 'Technical School' },
    { label: 'Trade School', value: 'Trade School' },
    { label: 'Tutoring Services', value: 'Tutoring Services' },
    { label: 'Vocational School', value: 'Vocational School' },

    { label: 'Accountant', value: 'Accountant' },
    { label: 'Auditing', value: 'Auditing' },
    { label: 'Bank/Credit Union', value: 'Bank/Credit Union' },
    { label: 'Bookkeeping', value: 'Bookkeeping' },
    { label: 'Cash Advances', value: 'Cash Advances' },
    { label: 'Collection Agency', value: 'Collection Agency' },
    { label: 'Insurance', value: 'Insurance' },
    { label: 'Investor', value: 'Investor' },
    { label: 'Other (Finance & Insurance)', value: 'Other (Finance & Insurance)' },
    { label: 'Pawn Brokers', value: 'Pawn Brokers' },
    { label: 'Tax Preparation', value: 'Tax Preparation' },

    { label: 'Alcohol/Tobacco Sales', value: 'Alcohol/Tobacco Sales' },
    { label: 'Alcoholic Beverage Manufacturing', value: 'Alcoholic Beverage Manufacturing' },
    { label: 'Bakery', value: 'Bakery' },
    { label: 'Caterer', value: 'Caterer' },
    { label: 'Food/Beverage Manufacturing', value: 'Food/Beverage Manufacturing' },
    { label: 'Grocery/Convenience Store(Gas Station)', value: 'Grocery/Convenience Store(Gas Station)' },
    { label: 'Grocery/Convenience Store(No Gas Station)', value: 'Grocery/Convenience Store(No Gas Station)' },
    { label: 'Hotels/Motels(Casino)', value: 'Hotels/Motels(Casino)' },
    { label: 'Hotels/Motels(No Casino)', value: 'Hotels/Motels(No Casino)' },
    { label: 'Mobile Food Services', value: 'Mobile Food Services' },
    { label: 'Other (Food & Hospitality)', value: 'Other (Food & Hospitality)' },
    { label: 'Restaurant/Bar', value: 'Restaurant/Bar' },
    { label: 'Specialty Food(Fruit/Vegetables)', value: 'Specialty Food(Fruit/Vegetables)' },
    { label: 'Specialty Food(Meat)', value: 'Specialty Food(Meat)' },
    { label: 'Specialty Food(Seafood)', value: 'Specialty Food(Seafood)' },
    { label: 'Tobacco Product Manufacturing', value: 'Tobacco Product Manufacturing' },
    { label: 'Truck Stop', value: 'Truck Stop' },
    { label: 'Vending Machine', value: 'Vending Machine' },

    { label: 'Auctioneer', value: 'Auctioneer' },
    { label: 'Boxing/Wrestling', value: 'Boxing/Wrestling' },
    { label: 'Casino/Video Gaming', value: 'Casino/Video Gaming' },
    { label: 'Other (Gaming)', value: 'Other (Gaming)' },
    { label: 'Racetrack', value: 'Racetrack' },
    { label: 'Sports Agent', value: 'Sports Agent' },

    { label: 'Acupuncturist', value: 'Acupuncturist' },
    { label: 'Athletic Trainer', value: 'Athletic Trainer' },
    { label: 'Child/Youth Services', value: 'Child/Youth Services' },
    { label: 'Chiropractic Office', value: 'Chiropractic Office' },
    { label: 'Dentistry', value: 'Dentistry' },
    { label: 'Electrolysis', value: 'Electrolysis' },
    { label: 'Embalmer', value: 'Embalmer' },
    { label: 'Emergency Medical Services', value: 'Emergency Medical Services' },
    { label: 'Emergency Medical Transportation', value: 'Emergency Medical Transportation' },
    { label: 'Hearing Aid Dealers', value: 'Hearing Aid Dealers' },
    { label: 'Home Health Services', value: 'Home Health Services' },
    { label: 'Hospital', value: 'Hospital' },
    { label: 'Massage Therapy', value: 'Massage Therapy' },
    { label: 'Medical Office', value: 'Medical Office' },
    { label: 'Mental Health Services', value: 'Mental Health Services' },
    { label: 'Non Emergency Medical Transportation', value: 'Non Emergency Medical Transportation' },
    { label: 'Optometry', value: 'Optometry' },
    { label: 'Other (Health Services)', value: 'Other (Health Services)' },
    { label: 'Pharmacy', value: 'Pharmacy' },
    { label: 'Physical Therapy', value: 'Physical Therapy' },
    { label: 'Physicians Office', value: 'Physicians Office' },
    { label: 'Radiology', value: 'Radiology' },
    { label: 'Residential Care Facility', value: 'Residential Care Facility' },
    { label: 'Speech/Occupational Therapy', value: 'Speech/Occupational Therapy' },
    { label: 'Substance Abuse Services', value: 'Substance Abuse Services' },
    { label: 'Veterinary Medicine', value: 'Veterinary Medicine' },
    { label: 'Vocational Rehabilitation', value: 'Vocational Rehabilitation' },
    { label: 'Wholesale Drug Distribution', value: 'Wholesale Drug Distribution' },

    { label: 'Automotive Part Sales', value: 'Automotive Part Sales' },
    { label: 'Car Wash/Detailing', value: 'Car Wash/Detailing' },
    { label: 'Motor Vehicle Rental', value: 'Motor Vehicle Rental' },
    { label: 'Motor Vehicle Repair', value: 'Motor Vehicle Repair' },
    { label: 'New Motor Vehicle Sales', value: 'New Motor Vehicle Sales' },
    { label: 'Other (Motor Vehicle)', value: 'Other (Motor Vehicle)' },
    { label: 'Recreational Vehicle Sales', value: 'Recreational Vehicle Sales' },
    { label: 'Used Motor Vehicle Sales', value: 'Used Motor Vehicle Sales' },

    { label: 'Conservation Organizations', value: 'Conservation Organizations' },
    { label: 'Environmental Health', value: 'Environmental Health' },
    { label: 'Land Surveying', value: 'Land Surveying' },
    { label: 'Oil & Gas Distribution', value: 'Oil & Gas Distribution' },
    { label: 'Oil & Gas Extraction/Production', value: 'Oil & Gas Extraction/Production' },
    { label: 'Other (Natural Resources/Environmental)', value: 'Other (Natural Resources/Environmental)' },
    { label: 'Pipeline', value: 'Pipeline' },
    { label: 'Water Well Drilling', value: 'Water Well Drilling' },

    { label: 'Other(Business Type Not Listed)', value: 'Other(Business Type Not Listed)' },

    { label: 'Animal Boarding', value: 'Animal Boarding' },
    { label: 'Barber Shop', value: 'Barber Shop' },
    { label: 'Beauty Salon', value: 'Beauty Salon' },
    { label: 'Cemetery', value: 'Cemetery' },
    { label: 'Diet Center', value: 'Diet Center' },
    { label: 'Dry cleaning/Laundry', value: 'Dry cleaning/Laundry' },
    { label: 'Entertainment/Party Rentals', value: 'Entertainment/Party Rentals' },
    { label: 'Event Planning', value: 'Event Planning' },
    { label: 'Fitness Center', value: 'Fitness Center' },
    { label: 'Florist', value: 'Florist' },
    { label: 'Funeral Director', value: 'Funeral Director' },
    { label: 'Janitorial/Cleaning Services', value: 'Janitorial/Cleaning Services' },
    { label: 'Massage/Day Spa', value: 'Massage/Day Spa' },
    { label: 'Nail Salon', value: 'Nail Salon' },
    { label: 'Other (Personal Services)', value: 'Other (Personal Services)' },
    { label: 'Personal Assistant', value: 'Personal Assistant' },
    { label: 'Photography', value: 'Photography' },
    { label: 'Tanning Salon', value: 'Tanning Salon' },

    { label: 'Home Inspection', value: 'Home Inspection' },
    { label: 'Interior Design', value: 'Interior Design' },
    { label: 'Manufactured Housing', value: 'Manufactured Housing' },
    { label: 'Mortgage Company', value: 'Mortgage Company' },
    { label: 'Other (Real Estate & Housing)', value: 'Other (Real Estate & Housing)' },
    { label: 'Property Management', value: 'Property Management' },
    { label: 'Real Estate Broker/Agent', value: 'Real Estate Broker/Agent' },
    { label: 'Warehouse/Storage', value: 'Warehouse/Storage' },

    { label: 'Attorney', value: 'Attorney' },
    { label: 'Bail Bonds', value: 'Bail Bonds' },
    { label: 'Court Reporter', value: 'Court Reporter' },
    { label: 'Drug Screening', value: 'Drug Screening' },
    { label: 'Locksmith', value: 'Locksmith' },
    { label: 'Other (Safety/Security & Legal)', value: 'Other (Safety/Security & Legal)' },
    { label: 'Private Investigator', value: 'Private Investigator' },
    { label: 'Security Guard', value: 'Security Guard' },
    { label: 'Security System Services', value: 'Security System Services' },

    { label: 'Air Transportation', value: 'Air Transportation' },
    { label: 'Boat Services', value: 'Boat Services' },
    { label: 'Limousine Services', value: 'Limousine Services' },
    { label: 'Other (Transportation)', value: 'Other (Transportation)' },
    { label: 'Taxi Services', value: 'Taxi Services' },
    { label: 'Towing', value: 'Towing' },
    { label: 'Truck Transportation(Fuel)', value: 'Truck Transportation(Fuel)' },
    { label: 'Truck Transportation(Non Fuel)', value: 'Truck Transportation(Non Fuel)' }
];
